# Ejemplos

POST https://api-mongodb-dev-hmzf.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Mesa", 
    "precio": 20 
}

### 

POST https://api-mongodb-dev-hmzf.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Silla", 
    "precio": 21 
}


### 

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

###

PUT https://api-mongodb-dev-hmzf.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Armario", 
    "precio": 32 
}

### 

POST https://api-mongodb-dev-hmzf.3.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Cama", 
    "precio": 69 
}

###

PUT https://api-mongodb-dev-hmzf.3.us-1.fl0.io/api/productos/654bb60af6300dc80f83ae38 HTTP/1.1
content-type: application/json

{ 
    "nombre": "Ordenador", 
    "precio": 90 
}